name: Build EDOPro
on: [push, pull_request]
env:
  COVERS_URL: ${{ secrets.COVERS_URL }}
  DEPENDENCIES_BASE_URL: https://github.com/edo9300/edopro-vcpkg-cache/releases/latest/download
  DEPLOY_DIR: deploy
  DEPLOY_REPO: ${{ secrets.DEPLOY_REPO }}
  DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
  DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID }}
  FIELDS_URL: ${{ secrets.FIELDS_URL }}
  PICS_URL: ${{ secrets.PICS_URL }}
  UPDATE_URL: ${{ secrets.UPDATE_URL }}
jobs:
  Linux-aarch64-gcc-7-5-0:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    env:
      DEPLOY_BRANCH: travis-linux-aarch64
      TRAVIS_OS_NAME: linux
      BUILD_CONFIG: release
      ARCH: arm64
    steps:
    - name: Set custom env vars
      shell: bash
      run: |
        echo "VCPKG_ROOT=$PWD/vcpkg" >> $GITHUB_ENV
        echo "VCPKG_CACHE_7Z_URL=$DEPENDENCIES_BASE_URL/installed_aarch64-linux.7z" >> $GITHUB_ENV
    - name: Get apt packages
      shell: bash
      run: |
        apt update
        apt install sudo
        sudo apt remove libsqlite3-dev
        sudo apt install -y g++ build-essential curl p7zip-full p7zip-rar zip git gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install premake
      shell: bash
      run: ./travis/install-premake5.sh
    - name: Install dependencies
      shell: bash
      run: |
        ./travis/dependencies.sh
    - name: Build
      env:
        CC: /usr/bin/aarch64-linux-gnu-gcc
        CXX: /usr/bin/aarch64-linux-gnu-g++
      shell: bash
      run: ./travis/build.sh
    - name: Predeploy
      shell: bash
      run: ./travis/predeploy.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: build-aarch64
        path: deploy
